development:
  adapter: mysql2
  encoding: utf8
  database: stockistrewards_development
  username: root
  password: ""
  host: localhost
  port: 3306
  pool: 30

staging:
  adapter: mysql2
  encoding: utf8
  database: stockistrewards_staging
  username: root
  password: fadsdas234dfsada
  host: localhost
  port: 3306
  pool: 30

production:
  adapter: mysql2
  encoding: utf8
  database: stockistrewards_production
  username: root
  password: fadsdas234dfsada
  host: localhost
  port: 3306
  pool: 30
